name: Build and Deploy

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
         cd /home/ubuntu/cc-landing-page
         git pull origin master
         docker compose up --build -d
